.TH TUXTYPE 1 "Feb 6, 2001"
.SH NAME
tuxtype \- TuxTyping typing tutor
.SH SYNOPSIS
.BI tuxtype " [OPTION] ..."
.SH DESCRIPTION
This manual page documents briefly the
.B tuxtype
command.
.PP
.B TuxTyping
is an educational typing tutorial game starring 
Tux, the Linux Penguin. The player guides Tux to eat fish
which are falling from the top of the screen. Each fish has a
letter written on it. When the player presses the
corresponding key, Tux will position himself to eat the fish.
The game is intended for children learning to type, though it
does have higher difficulty levels which even experienced
typers may find challenging.
.SH OPTIONS
.TP
.BI \-h ", " \-\-help ", " \-help
Prints this help message
.TP
.BI \-f ", " \-\-fullscreen
Selects fullscreen display (default)
.TP
.BI \-w ", " \-\-window
Selects windowed display (not fullscreen)
.TP
.BI \-s ", " \-\-sound
Allow in\-game sounds (default)
.TP
.BI \-ns ", " \-\-nosound
Disables in\-game sounds
.TP
.BI \-sp ", " \-\-speed
Speed up gameplay (for use on slower
machines)
.TP
.BI \-st ", " \-\-static
Static (non\-scrolling) setting (helps on systems
where mouse disappears)
.TP
.BI \-v ", " \-\-version
Display version number and exit
.TP
.BI \-vb ", " \-\-verbose
Select verbose output (for debugging)
(Warning! Verbose is /very/ verbose!)
.SH AUTHORS
Sam Hart <hart@geekcomix.com>. Man page written by Laurence J. Lane <ljlane@debian.org>.
